datasource:
  dbone:
    url: jdbc:h2:mem:test:user_db_one;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL
    maxActive: 5
    max-idle: 2
    min-idle: 1
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: false
      auto: update
    schema: init-schema-test.sql
  dbtwo:
    url: jdbc:h2:mem:test:user_db_two;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL
    maxActive: 5
    max-idle: 2
    min-idle: 1
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: false
      auto: update
    schema: init-schema-test.sql